# Site settings
title: Amy Tsai
email: astsai127@gmail.com
description: Researcher at Stanford University<br />MS1 at UC Davis School of Medicine
baseurl: "/astsai.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Amy Tsai
street_address: 300 Pasteur Drive
city: Stanford
state: CA
zip_code: 94305
country: United States of America
#phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/astsai
googleplus_url: https://scholar.google.com/citations?user=1jxR9JIAAAAJ&hl=en
instagram_url:
linkedin_url: https://www.linkedin.com/in/astsai/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/amytsaii

# Build settings
markdown: kramdown

sass:
style: compressed
